### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by living1069** [yanlinlin82/ggvenn#1]
When arranging with cowplot::plot_grid, two venn plot will change the ratio for each plot. Could the ggvenn fix the ratio of width and height for each plots?
Thanks!
Below is what I got.
![image](https://user-images.githubusercontent.com/12094643/67449778-e10ab200-f64d-11e9-9908-48b59a5b3371.png)

**Comment by yanlinlin82** [comment]
Thank you for your interest in this package! How about to try `coord_fixed()`?

**Comment by yanlinlin82** [comment]
I guess this could be done by calling ggplot function `coord_fixed()`, so I will close this now.

Besides, any other suggestions are welcome!
