### ISSUE TITLE
Great Pkg but get error msg in example code.

### ISSUE THREAD

**Issue by sfd99** [yanlinlin82/ggvenn#10]
_Hi LinLin!_

**ggVenn** is really a GREAT Pkg, 
but I get an error msg 
using the GIThub page example code:

\# use data.frame as input...
d <- tibble(value   = c(1, 2, 3, 5, 6, 7, 8, 9, 10, 12, 13),
            `Set 1` = c(T, F, T, T, F, T, F, T, F,  F,  F),
            `Set 2` = c(T, F, F, T, F, F, F, T, F,  F,  T),
            `Set 3` = c(T, T, F, F, F, F, T, T, F,  F,  F),
            `Set 4` = c(F, F, F, F, T, T, F, F, T,  T,  F))

> d %>% ggvenn(aes(A = \`Set 1\`,  B = \`Set 2\`))
_**Error:** Must subset columns with a valid subscript vector.
x Subscript `columns[[1]]` has the wrong type `quosure/formula`.
 It must be logical, numeric, or character._

Help!
**Sfd99
San Francisco
R / Rstudio / Ubuntu Linux 20.04 (all latest versions).**

**Comment by yanlinlin82** [comment]
Thank you for your interests and reporting this.

There are two ways for using ggvenn.

**Method 1: (as a simple function)**

```r
d %>% ggvenn(c("Set 1", "Set 2"))  # _NOT USE_ `aes()`
```

**Method 2: (in ggplot way)**

```r
d %>% ggplot(aes(A = `Set 1`, B = `Set 2`)) + geom_venn()  # _USE_ `aes()`
```
