### ISSUE TITLE
Request: higher precision option for percentages

### ISSUE THREAD

**Issue by sheikki** [yanlinlin82/ggvenn#11]
Because sometimes one decimal digit precision isn't enough..

**Comment by yanlinlin82** [comment]
I have added a new parameter (digits) and released a new version ([0.1.6](https://github.com/yanlinlin82/ggvenn/releases/tag/v0.1.6)). You may try it like:

```r
ggvenn(d, digits = 2)
```

or

```r
ggplot(d) + geom_venn(aes(A = `Set 1`, B = `Set 2`), digits = 2)
```
