### ISSUE TITLE
using ggvenn in jamovi

### ISSUE THREAD

**Issue by sbalci** [yanlinlin82/ggvenn#16]
Dear @yanlinlin82,
I am developing [some modules](https://www.serdarbalci.com/ClinicoPathJamoviModule/) for [jamovi.org ](https://www.jamovi.org/)
I think ggvenn will be useful for clinical researchers, so I have added your package to see if it will work inside jamovi.
I will try to add arguments as well.
Please let me know what you think, and please check if the reference I have given is appropriate.

Best wishes

<img width="1268" alt="Screen Shot 2021-02-08 at 12 22 12" src="https://user-images.githubusercontent.com/7208830/107200820-3b797e80-6a09-11eb-9719-3677885f1eac.png">

<img width="641" alt="Screen Shot 2021-02-08 at 12 34 54" src="https://user-images.githubusercontent.com/7208830/107201464-10dbf580-6a0a-11eb-82b2-92c650fd6949.png">

**Comment by yanlinlin82** [comment]
Thank you very much! The citation is all right for me. PRs and suggestions for this package are welcome.

**Comment by sbalci** [comment]
added to jamovi library and ready to use now :)
