### ISSUE TITLE
ggvenn - warning message - guides(<scale> = FALSE)` is deprecated

### ISSUE THREAD

**Issue by AureliaKurtis** [yanlinlin82/ggvenn#20]
Hello, I was using the ggvenn function without any problems before, but I recently got this error messsage with the same code. Please find an example that give me the same wrning message.

`A=c("blue", "green", 'purple', "orange")
B=c("blue", "yellow", "black", "pink")
C=c("pink", "red", "orange", "green")
D=c("green", "blue", "orange")

ListeVenn=list(A=A, B=B, C=C, D=D)

ggvenn(ListeVenn)

"Warning message:
`guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead." `

The veen diagramm is made but without any colours and some lines are missing

Below is the plot I am obtaining following the warning message

![8545](https://user-images.githubusercontent.com/86610152/123645786-ebb81a00-d826-11eb-9ffc-8a9c43e3eca8.PNG)

**Comment by yanlinlin82** [comment]
Hi @AureliaKurtis,

Thank you very much for reporting this bug! I have solved the problem by correcting the misuse of the 'fill' parameter in the code. Would you please help to take a try and confirm it?

You may upgrade to the latest version (v0.1.9) by following command:

```r
# install.packages("devtools")
devtools::install_github("yanlinlin82/ggvenn")
```

I will upload the latest version to CRAN later.

**Comment by AureliaKurtis** [comment]
Hi @yanlinlin82 

Thank you so much, the problem is solved with this correction.
