### ISSUE TITLE
put commas in large numbers - ggvenn

### ISSUE THREAD

**Issue by hnaeem** [yanlinlin82/ggvenn#24]
I was wondering how to display large numbers separated by a comma in ggvenn? Any help will be appreciated?

**Comment by fkgruber** [comment]
see https://github.com/yanlinlin82/ggvenn/pull/42

**Comment by yanlinlin82** [comment]
Thanks to @fkgruber. Now, we can use the 'comma_sep' option to add commas in large numbers.

Here's a quick example:

```r
# Install the latest version from GitHub if required
# devtools::install_github("yanlinlin82/ggvenn")

library(ggvenn)

ggvenn(data_frame(A = rep(TRUE, 123456), B = rep(c(TRUE, FALSE), 123456/2)), comma_sep = TRUE)
```
