### ISSUE TITLE
Set names not shown fully

### ISSUE THREAD

**Issue by AidenSb** [yanlinlin82/ggvenn#25]
Hi,
Thanks for the beautiful package.
Any ideas on how can I adjust the position of the set names? for longer set names it doesn't show them fully no matter the plot size. (e.g test1test2test3test4 in this example)
Thanks

![image](https://user-images.githubusercontent.com/51430243/145128831-39fe568d-2edf-496c-bc74-eb65f7fc9ae1.png)

**Comment by MVesuviusC** [comment]
Hey, I found a work-around for this:
```
venn_plot <- ggvenn::ggvenn(list_of_four_vectors)

venn_plot$layers[[3]]$data$x <- c(-1, -0.8, 0.8, 1)
```
Adjust the numeric vector to push things where you want
You may need to use fewer/different positions if you have less than a four-way Venn diagram. You can just run `venn_plot$layers[[3]]$data$x` to get an idea of the current label positions

**Comment by zxgsy520** [comment]
![image](https://github.com/yanlinlin82/ggvenn/assets/36355222/b47839fb-79d9-46ec-b8e1-5bbed7f9bc8c)
Save using ggsave. The name display is incomplete. May I ask how to handle it. Thank you!

**Comment by yanlinlin82** [comment]
Thank you for asking!

So far, a workaround for this problem is manually setting the coordinates boundary. Here goes an example:

```r
library(ggvenn)

a = list('a very very long set name' = 1:5, 'another set' = 4:7)
ggvenn(a) + coord_cartesian(xlim = c(-5, 5), ylim = c(-5, 5))  # modify these numbers to refine
```

**Comment by dnldelarosa** [comment]
This issue has been resolved by the following pull request: https://github.com/yanlinlin82/ggvenn/pull/47

The new padding argument in the ggvenn function allows users to control the padding around the Venn diagram, which addresses the issue of truncated labels.

Thank you for reporting this issue!
