### ISSUE TITLE
Including total on the set labels

### ISSUE THREAD

**Issue by JesseRop** [yanlinlin82/ggvenn#28]
Is it possible to include the total count next to the set labels? Thanks.

**Comment by ivakru** [comment]
This is a common comment that I get when showing the diagrams from ggvenn directly.

**Comment by dnldelarosa** [comment]
This issue has been resolved by the following pull request: #48 

The new `show_set_totals` argument in the `ggvenn` function allows users to display the total count and/or percentage for each set in the Venn diagram, providing the functionality requested in this issue.

Thank you for reporting this issue and helping to improve `ggvenn`!
