### ISSUE TITLE
problem with the diagramm

### ISSUE THREAD

**Issue by ArthurPERE** [yanlinlin82/ggvenn#3]
Hello,

I use your package but I have a bug when I use the diagramme in 4d, there is an intersection where the number is false.

Take this test file [test.txt](https://github.com/yanlinlin82/ggvenn/files/3968786/test.txt), 

```
library(data.table)
library(tidyverse)
library(ggvenn)

test = fread(test.txt)

test %>% ggvenn()

nrow(test[A == T & B == T & C == F & D==T])
```

The problem is on the intersection of A, B and D, your diagramme indicate 2 instead of 13 like the `nrow(test[A == T & B == T & C == F & D==T])` indicate. This is the image I obtained with this test : ![test.png](https://user-images.githubusercontent.com/9747808/70920867-91c87880-2023-11ea-951d-24ae1cca0149.png).

Thanks,

**Comment by yanlinlin82** [comment]
Thank you very much for reporting this. I will check that.

**Comment by yanlinlin82** [comment]
I have fixed the bug. Please reinstall the latest version (0.1.1) and help to try again:

```r
devtools::install_github("yanlinlin82/ggvenn", force = TRUE)
```

**Comment by ArthurPERE** [comment]
It is working. 

Thank you
