### ISSUE TITLE
Can I change font family?

### ISSUE THREAD

**Issue by khb3850** [yanlinlin82/ggvenn#34]
I'm Hanbeen Kim.

Thank you for developing helpful tool "ggvenn".

I would like to change the font family from default setting to "Times New Roman".

Is there any possible way to change?

Sincerely,

Hanbeen Kim

**Comment by yanlinlin82** [comment]
Since `theme(text = element_text(family = "Serif"))` does not affect `geom_text()`, you may try some other hacking tricks. For example (`ggfun::set_font()`):

```r
if (!require(ggfun)) install.packages("ggfun")

library(ggvenn)
a <- list(A = 1:5, B = 4:6)
ggvenn(a) %>% ggfun::set_font(family = "Serif")
```
