### ISSUE TITLE
Adding a website/pkgdown

### ISSUE THREAD

**Issue by sdhutchins** [yanlinlin82/ggvenn#36]
Hey, @yanlinlin82!

I like this package a lot. It's easy to use.

Have you considered adding a [pkdown website/documentation](https://pkgdown.r-lib.org/) as well as some contributing docs?

It's pretty straightforward to set up, and I think it'd help the package's visibility and make it a little easier to look at the api.

**Comment by yanlinlin82** [comment]
Hi, @sdhutchins!

Thank you very much for the suggestion! I will consider that.

**Comment by sdhutchins** [comment]
Let me know if I can help at all.

**Comment by yanlinlin82** [comment]
Pkgdown website is ready: <https://yanlinlin82.github.io/ggvenn/>

Thank @sdhutchins again for the suggestion!

**Comment by sdhutchins** [comment]
Looks amazing!
