### ISSUE TITLE
Increased judgment of overlapping relationships

### ISSUE THREAD

**Issue by WangYe661** [yanlinlin82/ggvenn#38]
For example, if there is a set that contains all of the elements, draw the other circles inside that set

**Comment by yanlinlin82** [comment]
For two sets, option `auto_scale=TRUE` could achieve this.

```r
library(ggvenn)

ggvenn(list(A=1:5, B=3:5), auto_scale=TRUE)
```

I am now continuing to work on other cases.

**Comment by WangYe661** [comment]
感谢您的解答
________________________________
发件人: Linlin Yan (颜林林) ***@***.***>
发送时间: Monday, January 22, 2024 2:37:48 PM
收件人: yanlinlin82/ggvenn ***@***.***>
抄送: YeWang ***@***.***>; Author ***@***.***>
主题: Re: [yanlinlin82/ggvenn] Increased judgment of overlapping relationships (Issue #38)


For two sets, option auto_scale=TRUE could achieve this.

library(ggvenn)

ggvenn(list(A=1:5, B=3:5), auto_scale=TRUE)

I am now continuing to work on other cases.

―
