### ISSUE TITLE
Request: Option to use names instead of counts in circles

### ISSUE THREAD

**Issue by rossellhayes** [yanlinlin82/ggvenn#4]
Excellent package! I was wondering if you would consider an option to use text labels instead of counts inside the circles, allowing the package to be used to create "traditional" Venn diagrams, such as the [first example from Wikipedia](https://en.wikipedia.org/wiki/Venn_diagram).

**Comment by yanlinlin82** [comment]
Thank you very much for your interest and kind suggestion! I will check and consider it.

**Comment by yanlinlin82** [comment]
I have committed a new version, which supports a `show_elements` option. Could you please help to try it?

Here goes a quick view of the new feature:

```r
# for list
list(A=1:3,B=3:6) %>%
   ggvenn(show_elements=TRUE)

# for data frame
data.frame(id=LETTERS[1:4],
           A=c(TRUE,TRUE,FALSE,FALSE),
           B=c(FALSE,TRUE,TRUE,TRUE)) %>%
  ggvenn(show_elements="id")

# for ggplot style using
data.frame(id=LETTERS[1:4],
           A=c(TRUE,TRUE,FALSE,FALSE),
           B=c(FALSE,TRUE,TRUE,TRUE)) %>%
  ggplot() +
  geom_venn(aes(A=A,B=B,label=id)) +
  coord_fixed() +
  theme_void()
```

**Comment by rossellhayes** [comment]
This is excellent! It fulfills my use case perfectly, much appreciated!
