### ISSUE TITLE
remove total count from plot

### ISSUE THREAD

**Issue by lmanchon** [yanlinlin82/ggvenn#41]
--Hi,

i use this code below:
ven <- ggplot(d, aes(A = `x`, B = `y`, C = `z`, D = `f`)) +
  geom_venn(
  stroke_color="grey",
  stroke_size = 0.5,
  stat = "identity",
  position = "identity",
  show_percentage = FALSE,
  fill_color=c("#8fd1b2", "#c4b3ab", "#a18073", "#409c9e"),
  set_name_color=c("#8fd1b2", "#c4b3ab", "#a18073", "#409c9e"),
  set_name_size = 6,
  text_size = 6,
  text_color = "black",
  fill_alpha = 0.5,
  stroke_alpha = 0.8,
  label_sep = ",",
  count_column = NULL,
  show_outside = c("auto", "none", "always"),
  auto_scale = FALSE) +
  theme_void() +
  ggtitle("blabla") +
   theme(plot.title = element_text(hjust = 0.5, size = rel(1.5))) +
  theme(legend.position="none")

and on my plot i have a total count (see on attached picture number 21615),
How to remove this count from picture ?

Thank you --
![venn](https://github.com/yanlinlin82/ggvenn/assets/3015749/0fab7819-c61c-4946-af4e-37b79cb6db70)

**Comment by yanlinlin82** [comment]
Hi, @lmanchon 

The number at the bottom is not the total count, but the outside count, which means these elements do not belong to any of the sets. In this case, there should be 21615 elements that do not belong to set x, y, z, and f.

To remove the number (21615), please try parameter `show_outside = "none"`.
