### ISSUE TITLE
"stroke_color" Multiple colors: is it possible?

### ISSUE THREAD

**Issue by Franelizabethgalvez** [yanlinlin82/ggvenn#49]
I would like to know if it is possible to define multiple colors for the stroke_color or if it is only possible to define one color.
This is my code: 

`a <- list(set1 = data[1:9, 2], set2 = data[1:3308, 3], set3 = data[1:2282, 4])`

`ggvenn(a, fill_color = c("seagreen2","orange1","gold"), fill_alpha= 0.5, stroke_size= 0.5, set_name_color=c("seagreen2","orange1","gold"), stroke_color=c("seagreen2","orange1","gold"), set_name_size=7,text_color="black", text_size=4.5, show_stats="c")` 

And this is the error I'm getting:

Error in `geom_polygon()`:
! Problem while setting up geom aesthetics.
 Error occurred in the 2nd layer.
Caused by error in `check_aesthetics()`:
! Aesthetics must be either length 1 or the same as the data (300).
✖ Fix the following mappings: `colour`.
Run `rlang::last_trace()` to see where the error occurred.
> 

the code only runs with `stroke_color="grey"`

Then I conclude that it is not possible to define more than one color. I would be grateful if someone could confirm this, or maybe there is another way to do this. 
[UV_Venn_SET_UP.txt](https://github.com/user-attachments/files/16821442/UV_Venn_SET_UP.txt)

Thank you very much!! ;)

**Comment by yanlinlin82** [comment]
So far, it is not possible to specify distinct colors for the sets because the stroke color (as well as alpha, size, and linetype) is hard-coded [here](https://github.com/yanlinlin82/ggvenn/blob/6e6380db1fa7a4dd5694a470f5eb848fe455f024/R/geom_venn.R#L164). If this feature is useful, I think we could consider adding it to the ggvenn package in future.

**Comment by yanlinlin82** [comment]
@Franelizabethgalvez Here goes a workaround in [another issue (#33)](https://github.com/yanlinlin82/ggvenn/issues/33#issuecomment-1356906704)

**Comment by Franelizabethgalvez** [comment]
Thanks @yanlinlin82! Yes, totally agree; please consider adding multiple colors to stroke_color ;)
